New-Item -Path '.\pagina-inicial.html' -ItemType File -Force
New-Item -Path '.\produtos\lista-produtos.html' -ItemType File -Force
New-Item -Path '.\produtos\cadastro-carro.html' -ItemType File -Force
New-Item -Path '.\produtos\carro-prisma.html' -ItemType File -Force
New-Item -Path '.\produtos\carro-gol.html' -ItemType File -Force
New-Item -Path '.\produtos\carro-celta.html' -ItemType File -Force
New-Item -Path '.\produtos\carro-palio.html' -ItemType File -Force
New-Item -Path '.\fornecedores\lista-fornecedores.html' -ItemType File -Force
New-Item -Path '.\fornecedores\cadastro-fornecedor.html' -ItemType File -Force
New-Item -Path '.\fornecedores\fiat.html' -ItemType File -Force
New-Item -Path '.\fornecedores\chevrolet.html' -ItemType File -Force
New-Item -Path '.\fornecedores\volks.html' -ItemType File -Force
New-Item -Path '.\clientes\lista-clientes.html' -ItemType File -Force
New-Item -Path '.\clientes\cadastro-clientes.html' -ItemType File -Force
New-Item -Path '.\clientes\fulano.html' -ItemType File -Force
New-Item -Path '.\clientes\ciclano.html' -ItemType File -Force
New-Item -Path '.\clientes\beltrano.html' -ItemType File -Force
New-Item -Path '.\funcionarios\lista-funcionarios.html' -ItemType File -Force
New-Item -Path '.\funcionarios\cadastro-funcionarios.html' -ItemType File -Force
New-Item -Path '.\funcionarios\funcionario-joao.html' -ItemType File -Force
New-Item -Path '.\funcionarios\funcionario-maria.html' -ItemType File -Force
New-Item -Path '.\funcionarios\funcionario-pedro.html' -ItemType File -Force