USE master
GO

DROP DATABASE IF EXISTS BANCO_DB
GO

CREATE DATABASE BANCO_DB
GO

USE BANCO_DB
GO

CREATE TABLE [dbo].[CLIENTE]
(
    [CPF] [bigint] NOT NULL,
    [NOME] [varchar](250) NOT NULL,
    [DATA_NASCIMENTO] [date] NOT NULL,
    CONSTRAINT [PK_CLIENTE] PRIMARY KEY (CPF)
)
GO
CREATE TABLE [dbo].[CONTA]
(
    [NUMERO] [bigint] NOT NULL,
    [DIGITO] [int] NOT NULL,
    [AGENCIA] [varchar](5) NOT NULL,
    [TIPO_CONTA] [int] NOT NULL,
    [SALDO] [decimal](11, 2) NOT NULL,
    [LIMITE] [decimal](11, 2) NULL,
    [DATA_ABERTURA] [date] NOT NULL,
    [CESTA] [int] NULL,
    [CPF_CLIENTE] [bigint] NULL,
    CONSTRAINT [PK_CONTA] PRIMARY KEY ([NUMERO]),
    CONSTRAINT [FK_CLIENTE_CONTA] FOREIGN KEY ([CPF_CLIENTE]) REFERENCES [dbo].[CLIENTE]([CPF])
)
 GO
CREATE TABLE [dbo].[CONTRATO]
(
    [NUMERO] [bigint] NOT NULL,
    [TIPO_CONTRATO] [int] NULL,
    [QUANTIDADE_PARCELAS] [int] NULL,
    [VALOR_TOTAL] [decimal](11, 2) NOT NULL,
    [VALOR_PARCELA] [decimal](11, 2) NULL,
    [DATA_INICIO] [date] NOT NULL,
    [DATA_FIM] [date] NOT NULL,
    [CPF_CLIENTE] [bigint] NULL,
    CONSTRAINT [PK_CONTRATO] PRIMARY KEY ([NUMERO]),
    CONSTRAINT [FK_CLIENTE_CONTRATO] FOREIGN KEY ([CPF_CLIENTE]) REFERENCES [dbo].[CLIENTE]([CPF])
)
GO
INSERT INTO [dbo].[CLIENTE] ([CPF], [NOME], [DATA_NASCIMENTO])
VALUES
    (809123546, 'Alberto Rodrigues', '2000-02-12'),
    (234423421, 'Antonio Silva', '1987-03-22'),
    (123211122, 'Roberto Alves', '1953-05-15');